server:
  port: 8080
  servlet:
    context-path:
  error:
    include-stacktrace: never

spring:
  profiles:
    active: @spring.profiles.active@
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: "jdbc:mysql://localhost:3306/javainventario"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: "dcevedo"
    password: "jandro07"
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: "jdbc:mysql://localhost:3306/javainventario"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: "root"
    password: "mibase1"