server:
  port: 8080
  servlet:
    context-path:
  error:
    include-stacktrace: never

spring:
  profiles:
    active: @spring.profiles.active@
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${PROD_URL}
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: ${PROD_USERNAME}
    password: ${PROD_PASSWORD}
server:
  port: 8443
  ssl:
    enabled: true
    certificate: ${CERTIFICATEPATH}
    certificate-private-key: ${CERTIFICATEPK} 
    trust-certificate: ${CERTIFICATETRUST}
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${DEV_URL}
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: ${DEV_USERNAME}
    password: ${DEV_PASSWORD}