spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/javainventario"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: "root"
    password: "mibase1"

server:
  port: 8080
  servlet:
    context-path: